### ISSUE TITLE
初回ミュート解除時に効果音が一気に流れる。

### ISSUE THREAD

**Issue by comefrombottom** [Raclamusi/OpenSiv3D#6]
**予期しない動作の内容 | Describe the unexpected behavior**
ミュートになってる時に流れた効果音が、最初にミュート解除した瞬間全部流れ出す。
公式のv0.6.6で作ったもので確認しました。
https://comefrombottom.github.io/ColorMix-Web/
**再現方法 | To Reproduce**
iPhone,Android,iPadでミュートのまま効果音を再生させ、ミュートを解除。最初に解除したときしか起きない。
https://discord.com/channels/443310697397354506/998714483612602489/1236504508914339840

**発生環境(モバイルの場合) | Smartphone (please complete the following information):**
自環境
 - デバイス | Device: iPhone8
 - OS: iOS
 - バージョン | Version:16.7.7
 - ブラウザ (Web 版) | Browser: Safari

他機種でも確認あり

**備考 | Additional context**
v0.6.13で起きるかは確かめていません。

**Comment by Raclamusi** [comment]
**調査メモ**

- AudioContext は始め suspend 状態なので、使用前に resume する必要がある
- AudioContext の resume にはユーザアクションが必要
- `document` または `#canvas` に対して `keydown`, `mousedown`, `touchstart` のいずれかのイベントが発生した時に、自動的に AudioContext を resume しようとする
- スマホでは `#canvas` をタッチした時に `touchstart` イベントは発生するものの、なぜか `mousedown` イベントが発生しない
- `touchstart` イベントではなぜか resume に失敗する
  - エラーメッセージ: <code>The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu</code>
- 以上のため、 `#canvas` 以外（フッター、プログレスバーなど）をタッチした時は正常に resume される
- v0.6.13 でも発生
- Chrome のスマホエミュレータでも再現する
- Firefox のスマホエミュレータでは再現しない

**Comment by nokotan** [comment]
Related:
- https://github.com/emscripten-core/emscripten/issues/19763
- https://developer.mozilla.org/ja/docs/Web/Security/User_activation

**Comment by Raclamusi** [comment]
https://github.com/Raclamusi/OpenSiv3D/blob/d91d1524eb874844ca7a5e8ec9c30da647803c34/Siv3D/lib/Web/jslib/Siv3D.UserAction.js#L30

この `e.preventDefault()` によって `mousedown` が発生しないようです。
これを消したところ、初回タッチ時に AudioContext が resume されました。

**Comment by Raclamusi** [comment]
修正しました。
初回の `touchend` イベントでオーディオが開始されます。
